sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx5cf8d845d3a75c94
    secret: e9f32896eb04c63109a7ff5492be666d
